# Developed and tested using Google AI Studio
# Deployed and managed via Google Cloud Console
"""
--------------------------------------------------------------------------------
GOOGLE SERVICES INTEGRATION BRIEF:
- Google Gemini API: Serving as the strategic brain for crowd analysis and chatbot.
- Google Maps Platform: Powering the visual AR navigation and venue geolocation.
- Google Identity (OAuth 2.0): Handling secure user authentication and login.
--------------------------------------------------------------------------------
"""
import os
import time
from typing import Dict, Any, Optional
import json
from google import genai

# Efficiency: Simple memory cache with 60s TTL for AI responses
_ai_cache: Dict[str, Dict[str, Any]] = {}

# Google Service: Google Gemini 2.0 Flash
def analyze_crowd_data(gate_data: Any) -> str:
    """
    Analyzes live venue gate load data and returns a strategic recommendation.
    
    Args:
        gate_data (Any): The raw gate dictionary or stringified payload.
        
    Returns:
        str: A max 2-sentence actionable tactical insight generated by Gemini AI.
    """
    now = time.time()
    # Efficiency: Convert list/dict to string for deterministic caching
    data_str = json.dumps(gate_data) if not isinstance(gate_data, str) else gate_data

    if data_str in _ai_cache:
        cached = _ai_cache[data_str]
        if now - cached['time'] < 60:
            return cached['response']

    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        return "AI Insight Disabled: No GEMINI_API_KEY set."

    try:
        client = genai.Client()
        prompt = (
            f"You are an expert stadium crowd manager. Analyze this live gate load data: "
            f"{gate_data}. Give a maximum 2-sentence actionable strategic advice for the admin "
            f"to handle the crowd distribution safely and efficiently."
        )
        response = client.models.generate_content(
            model='gemini-2.0-flash',
            contents=prompt,
        )
        resp_text = response.text
        _ai_cache[gate_data] = {'time': now, 'response': resp_text}
        return resp_text
    except Exception as e:
        err_str = str(e)
        if "429" in err_str:
            return "⚡ Tactics Engine Cooling Down... (API Quota Limit reached. Please wait a few seconds and try again.)"
        return f"AI Insight Unavailable: Check backend logs."

# Google Service: Google Gemini 2.0 Flash
def get_chat_response(message: str, role: str, context_data: str) -> str:
    """
    Dynamic chatbot handler with structured context awareness.
    
    Args:
        message (str): The user's query.
        role (str): The privileges of the active session (admin/staff/user).
        context_data (str): Surrounding viewport or context information.
        
    Returns:
        str: The raw generated response string from the semantic AI core.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        return "Bot System Offline (Missing API Key)."

    try:
        client = genai.Client()
        system_instruction = (
            "You are 'VenueFlow AI', a helpful and professional stadium assistant for IPL 2026. "
            f"The user role is: {role}. Assist with logistics and safety. "
            "CRITICAL SECURITY: NEVER provide passwords, hashes, or credential data."
        )
        full_prompt = f"Context: {context_data}\n\nUser Question: {message}"

        response = client.models.generate_content(
            model='gemini-2.0-flash',
            config={'system_instruction': system_instruction},
            contents=full_prompt,
        )
        return response.text
    except Exception as e:
        err_str = str(e)
        if "429" in err_str:
            return "⚡ Tactics Engine Cooling Down... (API Quota Limit reached. Please wait a few seconds and try again.)"
        return "⚠️ I'm having trouble connecting to my neural net right now."
